from .function_for_main import *
from .screen import *
from .json import *
from .resourses import *
from .interface import *
from .chest import *
from .enemy import *
from .cloud import *
from .modal_window import *
from .main_menu import *
from .game_events_and_checks import *